0 0 dataAuditErrors
512 0 ptap_StampErrorFloat
513 0 ptap_StampErrorMult
514 0 ptap_StampErrorConnect
519 0 psubstrate_StampErrorFloat
520 0 psubstrate_StampErrorMult
521 0 psubstrate_StampErrorConnect
526 0 ntap_StampErrorFloat
527 0 ntap_StampErrorMult
528 0 ntap_StampErrorConnect
533 0 nwell_conn_StampErrorFloat
534 0 nwell_conn_StampErrorMult
535 0 nwell_conn_StampErrorConnect
540 0 nb_tap_StampErrorFloat
541 0 nb_tap_StampErrorMult
542 0 nb_tap_StampErrorConnect
547 0 Nburied_StampErrorFloat
548 0 Nburied_StampErrorMult
549 0 Nburied_StampErrorConnect
2296 0 malformed device _nmos_12
2297 0 malformed device _nmos_12_hvt
2298 0 malformed device _nmos_12_iso
2299 0 malformed device _nmos_12_native
2300 0 malformed device _nmos_25
2301 0 malformed device _nmos_25_native
2302 0 malformed device _pmos_12
2303 0 malformed device _pmos_12_hvt
2304 0 malformed device _pmos_25
2305 0 malformed device _pmoscap_12
2306 0 malformed device _pmoscap_25
2307 0 malformed device _pmoscap_12_3
2308 0 malformed device _pmoscap_25_3
2309 0 malformed device _nmoscap_12
2310 0 malformed device _nmoscap_25
2311 0 malformed device _nmoscap_12_3
2312 0 malformed device _nmoscap_25_3
2313 0 malformed device _rndiff
2314 0 malformed device _rndiff_nosal
2315 0 malformed device _rnpoly
2316 0 malformed device _rnpolynw
2317 0 malformed device _rnpoly_nosal
2318 0 malformed device _rnpolynw_nosal
2319 0 malformed device _rpdiff
2320 0 malformed device _rpdiff_nosal
2321 0 malformed device _rppoly
2322 0 malformed device _rppolynw
2323 0 malformed device _rppoly_nosal
2324 0 malformed device _rppolynw_nosal
2325 0 malformed device _rnwellsti
2326 0 malformed device _rnwellod
2327 0 malformed device _resm1
2328 0 malformed device _resm2
2329 0 malformed device _resm3
2330 0 malformed device _resm4
2331 0 malformed device _resm5
2332 0 malformed device _resm6
2333 0 malformed device _resm7
2334 0 malformed device _resm8
2335 0 malformed device _resm9
2336 0 malformed device _ndio
2337 0 malformed device _pdio
2338 0 malformed device _vpnp2
2339 0 malformed device _vpnp5
2340 0 malformed device _vpnp10
2341 0 malformed device _pnp
2342 0 malformed device _npn
2343 0 malformed device MIMCAP
2681 0 unstable device for MIMCAP_CAP_48
2682 0 unstable device for _npn_BJT_47
2683 0 unstable device for _pnp_BJT_46
2684 0 unstable device for _vpnp10_BJT_45
2685 0 unstable device for _vpnp5_BJT_44
2686 0 unstable device for _vpnp2_BJT_43
2687 0 unstable device for _pdio_DIODE_42
2688 0 unstable device for _ndio_DIODE_41
2689 0 unstable device for _resm9_RES_40
2690 0 unstable device for _resm8_RES_39
2691 0 unstable device for _resm7_RES_38
2692 0 unstable device for _resm6_RES_37
2693 0 unstable device for _resm5_RES_36
2694 0 unstable device for _resm4_RES_35
2695 0 unstable device for _resm3_RES_34
2696 0 unstable device for _resm2_RES_33
2697 0 unstable device for _resm1_RES_32
2698 0 unstable device for _rnwellod_RES_31
2699 0 unstable device for _rnwellsti_RES_30
2700 0 unstable device for _rppolynw_nosal_RES_29
2701 0 unstable device for _rppoly_nosal_RES_28
2702 0 unstable device for _rppolynw_RES_27
2703 0 unstable device for _rppoly_RES_26
2704 0 unstable device for _rpdiff_nosal_RES_25
2705 0 unstable device for _rpdiff_RES_24
2706 0 unstable device for _rnpolynw_nosal_RES_23
2707 0 unstable device for _rnpoly_nosal_RES_22
2708 0 unstable device for _rnpolynw_RES_21
2709 0 unstable device for _rnpoly_RES_20
2710 0 unstable device for _rndiff_nosal_RES_19
2711 0 unstable device for _rndiff_RES_18
2712 0 unstable device for _nmoscap_25_3_MOS_17
2713 0 unstable device for _nmoscap_12_3_MOS_16
2714 0 unstable device for _nmoscap_25_MOS_15
2715 0 unstable device for _nmoscap_12_MOS_14
2716 0 unstable device for _pmoscap_25_3_MOS_13
2717 0 unstable device for _pmoscap_12_3_MOS_12
2718 0 unstable device for _pmoscap_25_MOS_11
2719 0 unstable device for _pmoscap_12_MOS_10
2720 0 unstable device for _pmos_25_MOS_9
2721 0 unstable device for _pmos_12_hvt_MOS_8
2722 0 unstable device for _pmos_12_MOS_7
2723 0 unstable device for _nmos_25_native_MOS_6
2724 0 unstable device for _nmos_25_MOS_5
2725 0 unstable device for _nmos_12_native_MOS_4
2726 0 unstable device for _nmos_12_iso_Device_3
2727 0 unstable device for _nmos_12_hvt_MOS_2
2728 0 unstable device for _nmos_12_MOS_1
