0 0 dataAuditErrors
1 0 non45Errors
2 0 offGridErrors
153 0 offGridShapeErrors: off grid polygon on layer Bondpad
155 0 offGridShapeErrors: off grid polygon on layer CapMetal
157 0 offGridShapeErrors: off grid polygon on layer Cont
159 0 offGridShapeErrors: off grid polygon on layer ESDdummy
161 0 offGridShapeErrors: off grid polygon on layer IND2dummy
163 0 offGridShapeErrors: off grid polygon on layer IND3dummy
165 0 offGridShapeErrors: off grid polygon on layer INDdummy
167 0 offGridShapeErrors: off grid polygon on layer M1Resdum
169 0 offGridShapeErrors: off grid polygon on layer M2Resdum
171 0 offGridShapeErrors: off grid polygon on layer M3Resdum
173 0 offGridShapeErrors: off grid polygon on layer M4Resdum
175 0 offGridShapeErrors: off grid polygon on layer M5Resdum
177 0 offGridShapeErrors: off grid polygon on layer M6Resdum
179 0 offGridShapeErrors: off grid polygon on layer M7Resdum
181 0 offGridShapeErrors: off grid polygon on layer M8Resdum
183 0 offGridShapeErrors: off grid polygon on layer M9Resdum
185 0 offGridShapeErrors: off grid polygon on layer Metal1_d
187 0 offGridShapeErrors: off grid polygon on layer Metal1_f
189 0 offGridShapeErrors: off grid polygon on layer Metal1_n
191 0 offGridShapeErrors: off grid polygon on layer Metal1_p
193 0 offGridShapeErrors: off grid polygon on layer Metal1_slot
195 0 offGridShapeErrors: off grid polygon on layer Metal2_d
197 0 offGridShapeErrors: off grid polygon on layer Metal2_f
199 0 offGridShapeErrors: off grid polygon on layer Metal2_n
201 0 offGridShapeErrors: off grid polygon on layer Metal2_p
203 0 offGridShapeErrors: off grid polygon on layer Metal2_slot
205 0 offGridShapeErrors: off grid polygon on layer Metal3_d
207 0 offGridShapeErrors: off grid polygon on layer Metal3_f
209 0 offGridShapeErrors: off grid polygon on layer Metal3_n
211 0 offGridShapeErrors: off grid polygon on layer Metal3_p
213 0 offGridShapeErrors: off grid polygon on layer Metal3_slot
215 0 offGridShapeErrors: off grid polygon on layer Metal4_d
217 0 offGridShapeErrors: off grid polygon on layer Metal4_f
219 0 offGridShapeErrors: off grid polygon on layer Metal4_n
221 0 offGridShapeErrors: off grid polygon on layer Metal4_p
223 0 offGridShapeErrors: off grid polygon on layer Metal4_slot
225 0 offGridShapeErrors: off grid polygon on layer Metal5_d
227 0 offGridShapeErrors: off grid polygon on layer Metal5_f
229 0 offGridShapeErrors: off grid polygon on layer Metal5_n
231 0 offGridShapeErrors: off grid polygon on layer Metal5_p
233 0 offGridShapeErrors: off grid polygon on layer Metal5_slot
235 0 offGridShapeErrors: off grid polygon on layer Metal6_d
237 0 offGridShapeErrors: off grid polygon on layer Metal6_f
239 0 offGridShapeErrors: off grid polygon on layer Metal6_n
241 0 offGridShapeErrors: off grid polygon on layer Metal6_p
243 0 offGridShapeErrors: off grid polygon on layer Metal6_slot
245 0 offGridShapeErrors: off grid polygon on layer Metal7_d
247 0 offGridShapeErrors: off grid polygon on layer Metal7_f
249 0 offGridShapeErrors: off grid polygon on layer Metal7_n
251 0 offGridShapeErrors: off grid polygon on layer Metal7_p
253 0 offGridShapeErrors: off grid polygon on layer Metal7_slot
255 0 offGridShapeErrors: off grid polygon on layer Metal8_d
257 0 offGridShapeErrors: off grid polygon on layer Metal8_f
259 0 offGridShapeErrors: off grid polygon on layer Metal8_n
261 0 offGridShapeErrors: off grid polygon on layer Metal8_p
263 0 offGridShapeErrors: off grid polygon on layer Metal8_slot
265 0 offGridShapeErrors: off grid polygon on layer Metal9_d
267 0 offGridShapeErrors: off grid polygon on layer Metal9_f
269 0 offGridShapeErrors: off grid polygon on layer Metal9_n
271 0 offGridShapeErrors: off grid polygon on layer Metal9_p
273 0 offGridShapeErrors: off grid polygon on layer Metal9_slot
275 0 offGridShapeErrors: off grid polygon on layer NPNdummy
277 0 offGridShapeErrors: off grid polygon on layer Nburied
279 0 offGridShapeErrors: off grid polygon on layer Nhvt
281 0 offGridShapeErrors: off grid polygon on layer Nimp
283 0 offGridShapeErrors: off grid polygon on layer Nwell
285 0 offGridShapeErrors: off grid polygon on layer Nzvt
287 0 offGridShapeErrors: off grid polygon on layer Oxide
289 0 offGridShapeErrors: off grid polygon on layer Oxide_thk
291 0 offGridShapeErrors: off grid polygon on layer PNPdummy
293 0 offGridShapeErrors: off grid polygon on layer Phvt
295 0 offGridShapeErrors: off grid polygon on layer Pimp
297 0 offGridShapeErrors: off grid polygon on layer Poly
299 0 offGridShapeErrors: off grid polygon on layer Psub
301 0 offGridShapeErrors: off grid polygon on layer ResWdum
303 0 offGridShapeErrors: off grid polygon on layer Resdum
305 0 offGridShapeErrors: off grid polygon on layer SiProt
307 0 offGridShapeErrors: off grid polygon on layer Via1
309 0 offGridShapeErrors: off grid polygon on layer Via2
311 0 offGridShapeErrors: off grid polygon on layer Via3
313 0 offGridShapeErrors: off grid polygon on layer Via4
315 0 offGridShapeErrors: off grid polygon on layer Via5
317 0 offGridShapeErrors: off grid polygon on layer Via6
319 0 offGridShapeErrors: off grid polygon on layer Via7
321 0 offGridShapeErrors: off grid polygon on layer Via8
323 0 non45 degree polygon on layer Bondpad
325 0 non45 degree polygon on layer CapMetal
327 0 non45 degree polygon on layer Cont
329 0 non45 degree polygon on layer ESDdummy
331 0 non45 degree polygon on layer IND2dummy
333 0 non45 degree polygon on layer IND3dummy
335 0 non45 degree polygon on layer INDdummy
337 0 non45 degree polygon on layer M1Resdum
339 0 non45 degree polygon on layer M2Resdum
341 0 non45 degree polygon on layer M3Resdum
343 0 non45 degree polygon on layer M4Resdum
345 0 non45 degree polygon on layer M5Resdum
347 0 non45 degree polygon on layer M6Resdum
349 0 non45 degree polygon on layer M7Resdum
351 0 non45 degree polygon on layer M8Resdum
353 0 non45 degree polygon on layer M9Resdum
355 0 non45 degree polygon on layer Metal1_d
357 0 non45 degree polygon on layer Metal1_f
359 0 non45 degree polygon on layer Metal1_n
361 0 non45 degree polygon on layer Metal1_p
363 0 non45 degree polygon on layer Metal1_slot
365 0 non45 degree polygon on layer Metal2_d
367 0 non45 degree polygon on layer Metal2_f
369 0 non45 degree polygon on layer Metal2_n
371 0 non45 degree polygon on layer Metal2_p
373 0 non45 degree polygon on layer Metal2_slot
375 0 non45 degree polygon on layer Metal3_d
377 0 non45 degree polygon on layer Metal3_f
379 0 non45 degree polygon on layer Metal3_n
381 0 non45 degree polygon on layer Metal3_p
383 0 non45 degree polygon on layer Metal3_slot
385 0 non45 degree polygon on layer Metal4_d
387 0 non45 degree polygon on layer Metal4_f
389 0 non45 degree polygon on layer Metal4_n
391 0 non45 degree polygon on layer Metal4_p
393 0 non45 degree polygon on layer Metal4_slot
395 0 non45 degree polygon on layer Metal5_d
397 0 non45 degree polygon on layer Metal5_f
399 0 non45 degree polygon on layer Metal5_n
401 0 non45 degree polygon on layer Metal5_p
403 0 non45 degree polygon on layer Metal5_slot
405 0 non45 degree polygon on layer Metal6_d
407 0 non45 degree polygon on layer Metal6_f
409 0 non45 degree polygon on layer Metal6_n
411 0 non45 degree polygon on layer Metal6_p
413 0 non45 degree polygon on layer Metal6_slot
415 0 non45 degree polygon on layer Metal7_d
417 0 non45 degree polygon on layer Metal7_f
419 0 non45 degree polygon on layer Metal7_n
421 0 non45 degree polygon on layer Metal7_p
423 0 non45 degree polygon on layer Metal7_slot
425 0 non45 degree polygon on layer Metal8_d
427 0 non45 degree polygon on layer Metal8_f
429 0 non45 degree polygon on layer Metal8_n
431 0 non45 degree polygon on layer Metal8_p
433 0 non45 degree polygon on layer Metal8_slot
435 0 non45 degree polygon on layer Metal9_d
437 0 non45 degree polygon on layer Metal9_f
439 0 non45 degree polygon on layer Metal9_n
441 0 non45 degree polygon on layer Metal9_p
443 0 non45 degree polygon on layer Metal9_slot
445 0 non45 degree polygon on layer NPNdummy
447 0 non45 degree polygon on layer Nburied
449 0 non45 degree polygon on layer Nhvt
451 0 non45 degree polygon on layer Nimp
453 0 non45 degree polygon on layer Nwell
455 0 non45 degree polygon on layer Nzvt
457 0 non45 degree polygon on layer Oxide
459 0 non45 degree polygon on layer Oxide_thk
461 0 non45 degree polygon on layer PNPdummy
463 0 non45 degree polygon on layer Phvt
465 0 non45 degree polygon on layer Pimp
467 0 non45 degree polygon on layer Poly
469 0 non45 degree polygon on layer Psub
471 0 non45 degree polygon on layer ResWdum
473 0 non45 degree polygon on layer Resdum
475 0 non45 degree polygon on layer SiProt
477 0 non45 degree polygon on layer Via1
479 0 non45 degree polygon on layer Via2
481 0 non45 degree polygon on layer Via3
483 0 non45 degree polygon on layer Via4
485 0 non45 degree polygon on layer Via5
487 0 non45 degree polygon on layer Via6
489 0 non45 degree polygon on layer Via7
491 0 non45 degree polygon on layer Via8
492 0 acute angle on layer Bondpad
493 0 acute angle on layer CapMetal
494 0 acute angle on layer ESDdummy
495 0 acute angle on layer IND2dummy
496 0 acute angle on layer IND3dummy
497 0 acute angle on layer INDdummy
498 0 acute angle on layer M1Resdum
499 0 acute angle on layer M2Resdum
500 0 acute angle on layer M3Resdum
501 0 acute angle on layer M4Resdum
502 0 acute angle on layer M5Resdum
503 0 acute angle on layer M6Resdum
504 0 acute angle on layer M7Resdum
505 0 acute angle on layer M8Resdum
506 0 acute angle on layer M9Resdum
507 0 acute angle on layer NPNdummy
508 0 acute angle on layer Nhvt
509 0 acute angle on layer PNPdummy
510 0 acute angle on layer Phvt
511 0 acute angle on layer Psub
512 0 acute angle on layer ResWdum
513 0 acute angle on layer Resdum
593 0 NZVT.X.4: Only one Oxide region may be in an Nzvt region
706 0 BONDPAD.L.1: Bondpad length must be >= 68.0 um
710 0 NBL.X.1: Nburied must have an Nwell isolation ring
714 0 NHVT.X.1: Nhvt to Oxide enclosure must be == 0.0 on all sides
718 0 PHVT.X.1: Phvt to Oxide enclosure must be == 0.0 on all sides
721 0 BONDPAD.O.1: Bondpads must contain Metal 1
726 0 BONDPAD.O.1: Bondpads must contain Metal 2
734 0 BONDPAD.O.1: Bondpads must contain Metal 3
739 0 BONDPAD.O.1: Bondpads must contain Metal 4
744 0 BONDPAD.O.1: Bondpads must contain Metal 5
749 0 BONDPAD.O.1: Bondpads must contain Metal 6
754 0 BONDPAD.O.1: Bondpads must contain Metal 7
759 0 BONDPAD.O.1: Bondpads must contain Metal 8
764 0 acute angle on layer Metal1
765 0 acute angle on layer Metal2
766 0 acute angle on layer Metal3
767 0 acute angle on layer Metal4
768 0 acute angle on layer Metal5
769 0 acute angle on layer Metal6
770 0 acute angle on layer Metal7
771 0 acute angle on layer Metal8
772 0 acute angle on layer Metal9
774 0 BONDPAD.O.1: Bondpads must contain Metal 9
815 0 NZVT.O.1: Nzvt to Oxide enclosure must be == 0.3
1066 0 BONDPAD.O.2: Bondpad Metal1/Metal2 intersection must contain Via 1
1071 0 BONDPAD.O.2: Bondpad Metal2/Metal3 intersection must contain Via 2
1076 0 BONDPAD.O.2: Bondpad Metal3/Metal4 intersection must contain Via 3
1081 0 BONDPAD.O.2: Bondpad Metal4/Metal5 intersection must contain Via 4
1086 0 BONDPAD.O.2: Bondpad Metal5/Metal6 intersection must contain Via 5
1091 0 BONDPAD.O.2: Bondpad Metal6/Metal7 intersection must contain Via 6
1096 0 BONDPAD.O.2: Bondpad Metal7/Metal8 intersection must contain Via 7
1101 0 BONDPAD.O.2: Bondpad Metal8/Metal9 intersection must contain Via 8
1497 0 POLY.SE.3: Poly width, between two contacts spaced > 25.0um, must be >= 0.14um
1509 0 BONDPAD.SP.5: Bondpad Metal1 slot to Bondpad Metal1 slot spacing must be == 1.50
1513 0 BONDPAD.W.4: Bondpad Metal1 slot width must be == 1.00
1524 0 BONDPAD.R.1: Minimum Bondpad Via1 inside Metal1 to Metal2 crossing must be >= 16.0
1529 0 BONDPAD.SP.5: Bondpad Metal2 slot to Bondpad Metal2 slot spacing must be == 1.50
1533 0 BONDPAD.W.4: Bondpad Metal2 slot width must be == 1.00
1544 0 BONDPAD.R.1: Minimum Bondpad Via2 inside Metal2 to Metal3 crossing must be >= 16.0
1549 0 BONDPAD.SP.5: Bondpad Metal3 slot to Bondpad Metal3 slot spacing must be == 1.50
1553 0 BONDPAD.W.4: Bondpad Metal3 slot width must be == 1.00
1564 0 BONDPAD.R.1: Minimum Bondpad Via3 inside Metal3 to Metal4 crossing must be >= 16.0
1569 0 BONDPAD.SP.5: Bondpad Metal4 slot to Bondpad Metal4 slot spacing must be == 1.50
1573 0 BONDPAD.W.4: Bondpad Metal4 slot width must be == 1.00
1584 0 BONDPAD.R.1: Minimum Bondpad Via4 inside Metal4 to Metal5 crossing must be >= 16.0
1589 0 BONDPAD.SP.5: Bondpad Metal5 slot to Bondpad Metal5 slot spacing must be == 1.50
1593 0 BONDPAD.W.4: Bondpad Metal5 slot width must be == 1.00
1604 0 BONDPAD.R.1: Minimum Bondpad Via5 inside Metal5 to Metal6 crossing must be >= 16.0
1609 0 BONDPAD.SP.5: Bondpad Metal6 slot to Bondpad Metal6 slot spacing must be == 1.50
1613 0 BONDPAD.W.4: Bondpad Metal6 slot width must be == 1.00
1624 0 BONDPAD.R.1: Minimum Bondpad Via6 inside Metal6 to Metal7 crossing must be >= 16.0
1629 0 BONDPAD.SP.5: Bondpad Metal7 slot to Bondpad Metal7 slot spacing must be == 1.50
1633 0 BONDPAD.W.4: Bondpad Metal7 slot width must be == 1.00
1644 0 BONDPAD.R.2: Minimum Bondpad Via7 inside Metal7 to Metal8 crossing must be >= 4.0
1649 0 BONDPAD.SP.5: Bondpad Metal8 slot to Bondpad Metal8 slot spacing must be == 1.50
1653 0 BONDPAD.W.4: Bondpad Metal8 slot width must be == 1.00
1658 0 BONDPAD.R.2: Minimum Bondpad Via8 inside Metal8 to Metal9 crossing must be >= 4.0
2339 0 OXIDE.L.1_OXIDE.L.2: Maximum Oxide length between two contacts (when the Oxide width is <= 0.18um) must be <= 22.0um and Maximum Oxide length between one contact and the end of the Oxide line (when the Oxide width is <= 0.18um) must be <= 11.0um
2367 0 BONDPAD.W.5: Bondpad Metal1 outside Metal1 ring width must be == 5.00
2395 0 BONDPAD.W.5: Bondpad Metal2 outside Metal2 ring width must be == 5.00
2423 0 BONDPAD.W.5: Bondpad Metal3 outside Metal3 ring width must be == 5.00
2451 0 BONDPAD.W.5: Bondpad Metal4 outside Metal4 ring width must be == 5.00
2479 0 BONDPAD.W.5: Bondpad Metal5 outside Metal5 ring width must be == 5.00
2507 0 BONDPAD.W.5: Bondpad Metal6 outside Metal6 ring width must be == 5.00
2535 0 BONDPAD.W.5: Bondpad Metal7 outside Metal7 ring width must be == 5.00
2563 0 BONDPAD.W.5: Bondpad Metal8 outside Metal8 ring width must be == 5.00
2583 0 VIA1.X.2: Metal1 must connect to Metal2 with >= 4 Via1 spaced < 0.30 um or >= 9 Via1 spaced < 0.60 um
2602 0 VIA2.X.2: Metal2 must connect to Metal3 with >= 4 Via2 spaced < 0.30 um or >= 9 Via2 spaced < 0.60 um
2622 0 VIA3.X.2: Metal3 must connect to Metal4 with >= 4 Via3 spaced < 0.30 um or >= 9 Via3 spaced < 0.60 um
2642 0 VIA4.X.2: Metal4 must connect to Metal5 with >= 4 Via4 spaced < 0.30 um or >= 9 Via4 spaced < 0.60 um
2662 0 VIA5.X.2: Metal5 must connect to Metal6 with >= 4 Via5 spaced < 0.30 um or >= 9 Via5 spaced < 0.60 um
2682 0 VIA6.X.2: Metal6 must connect to Metal7 with >= 4 Via6 spaced < 0.30 um or >= 9 Via6 spaced < 0.60 um
2702 0 VIA1.X.1: Metal1 must connect to Metal2 with >= 2 Via1 spaced < 0.30 um or >= 4 Via1 spaced < 0.60 um
2722 0 VIA2.X.1: Metal2 must connect to Metal3 with >= 2 Via2 spaced < 0.30 um or >= 4 Via2 spaced < 0.60 um
2742 0 VIA3.X.1: Metal3 must connect to Metal4 with >= 2 Via3 spaced < 0.30 um or >= 4 Via3 spaced < 0.60 um
2762 0 VIA4.X.1: Metal4 must connect to Metal5 with >= 2 Via4 spaced < 0.30 um or >= 4 Via4 spaced < 0.60 um
2782 0 VIA5.X.1: Metal5 must connect to Metal6 with >= 2 Via5 spaced < 0.30 um or >= 4 Via5 spaced < 0.60 um
2802 0 VIA6.X.1: Metal6 must connect to Metal7 with >= 2 Via6 spaced < 0.30 um or >= 4 Via6 spaced < 0.60 um
2808 0 BONDPAD.B.1: Bondpad Metal1 must have bevelled corners
2814 0 BONDPAD.B.1: Bondpad Metal2 must have bevelled corners
2820 0 BONDPAD.B.1: Bondpad Metal3 must have bevelled corners
2826 0 BONDPAD.B.1: Bondpad Metal4 must have bevelled corners
2832 0 BONDPAD.B.1: Bondpad Metal5 must have bevelled corners
2838 0 BONDPAD.B.1: Bondpad Metal6 must have bevelled corners
2844 0 BONDPAD.B.1: Bondpad Metal7 must have bevelled corners
2850 0 BONDPAD.B.1: Bondpad Metal8 must have bevelled corners
2856 0 BONDPAD.B.1: Bondpad Metal9 must have bevelled corners
2858 0 ptap_StampErrorFloat
2859 0 ptap_StampErrorMult
2860 0 ptap_StampErrorConnect
2865 0 psubstrate_StampErrorFloat
2866 0 psubstrate_StampErrorMult
2867 0 psubstrate_StampErrorConnect
2872 0 ntap_StampErrorFloat
2873 0 ntap_StampErrorMult
2874 0 ntap_StampErrorConnect
2879 0 nwell_conn_StampErrorFloat
2880 0 nwell_conn_StampErrorMult
2881 0 nwell_conn_StampErrorConnect
2886 0 nb_tap_StampErrorFloat
2887 0 nb_tap_StampErrorMult
2888 0 nb_tap_StampErrorConnect
2893 0 Nburied_StampErrorFloat
2894 0 Nburied_StampErrorMult
2895 0 Nburied_StampErrorConnect
2933 0 NBL.W.1: Nburied width must be >= 3.2 um
2935 0 NBL.E.1: Nburied to Nwell enclosure must be >= 0.4 um
2937 0 NBL.SP.1: Nburied to Nburied spacing must be >= 5.0 um
2940 0 NBL.SE.2: Nburied to Oxide spacing must be >= 2.2 um
2941 0 NBL.SE.2: Nburied to Oxide spacing must be >= 2.2 um
2942 0 NBL.SE.1: Nburied to non-related Nwell spacing must be >= 4.4 um
2947 0 NBL.SE.3: Nwell ring (on Nburied) to P+ Oxide spacing must be >= 0.5 um
2949 0 NBL.SE.3: Nwell ring (on Nburied) to P+ Oxide spacing must be >= 0.5 um
2953 0 NBL.SE.4: Nwell ring (on Nburied) to N+ Oxide spacing must be >= 0.4 um
2955 0 NBL.SE.4: Nwell ring (on Nburied) to N+ Oxide spacing must be >= 0.4 um
2957 0 NW.SP.1: Nwell to Nwell spacing (same potential) must be >= 0.6 um
2959 0 NW.SP.1: Nwell to Nwell spacing (same potential) must be >= 0.6 um
2962 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
2963 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
2965 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
2966 0 NW.W.1: Nwell width must be >= 0.6 um
2970 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
2971 0 NW.SE.1: Nwell to Oxide spacing must be >= 0.3 um
2974 0 NW.SE.2: Nwell to P+ Oxide spacing must be >= 0.3 um
2975 0 NW.SE.2: Nwell to P+ Oxide spacing must be >= 0.3 um
2980 0 NW.SE.3: Nwell to N+ 2.5V Oxide spacing must be >= 0.5 um
2981 0 NW.SE.3: Nwell to N+ 2.5V Oxide spacing must be >= 0.5 um
2986 0 NW.SE.4: Nwell to P+ 2.5V Oxide spacing must be >= 0.5 um
2987 0 NW.SE.4: Nwell to P+ 2.5V Oxide spacing must be >= 0.5 um
2992 0 NW.E.1: Nwell to N+ Oxide enclosure must be >= 0.12 um
2993 0 NW.E.2: Nwell to P+ Oxide enclosure must be >= 0.12 um
2995 0 NW.E.2: Nwell to P+ Oxide enclosure must be >= 0.12 um
2996 0 NW.E.3: Nwell to N+ 2.5V Oxide enclosure must be >= 0.7 um
2998 0 NW.E.3: Nwell to N+ 2.5V Oxide enclosure must be >= 0.7 um
2999 0 NW.E.4: Nwell to P+ 2.5V Oxide enclosure must be >= 0.7 um
3001 0 NW.E.4: Nwell to P+ 2.5V Oxide enclosure must be >= 0.7 um
3002 0 NWR.SE.1: Nwell (in resistor) to SiProt spacing must be >= 0.32 um
3004 0 NWR.E.1: Oxide to Nwell (in resistor) enclosure must be >= 1.2 um
3006 0 NWR.E.1: Oxide to Nwell (in resistor) enclosure must be >= 1.2 um
3008 0 NWR.E.2: Nwell (in resistor) to Cont enclosure must be >= 0.32 um
3010 0 NWR.E.2: Nwell (in resistor) to Cont enclosure must be >= 0.32 um
3011 0 NWR.O.1: SiProt to Nimp overlap must be >= 0.45 um
3012 0 NWR.X.1: Thick Oxide is NOT allowed over Nwell resistor
3013 0 OXIDE.W.1: Oxide width must be >= 0.1 um
3018 0 OXIDE.W.2.1.1: 1.2V N-channel gate width must be >= 0.12 um
3022 0 OXIDE.W.2.1.2: 2.5V N-channel gate width must be >= 0.15 um
3027 0 OXIDE.W.2.2.1: 1.2V P-channel gate width must be >= 0.12 um
3031 0 OXIDE.W.2.2.2: 2.5V P-channel gate width must be >= 0.15 um
3033 0 OXIDE.W.3: Oxide (45 degree) width must be >= 0.13 um
3035 0 OXIDE.SP.1: N+ Oxide to N+ Oxide spacing must be >= 0.15 um
3037 0 OXIDE.SP.2: P+ Oxide to P+ Oxide spacing must be >= 0.15 um
3042 0 OXIDE.SP.3: P+ Oxide to P+ Oxide spacing must be >= 0.15 um
3043 0 OXIDE.SE.1: Oxide to Oxide_thk spacing must be >= 0.28 um
3044 0 OXIDE.SP.4: Oxide bent 45 degree to Oxide spacing must be >= 0.18 um
3045 0 OXIDE.A.1: Oxide area must be >= 0.06 um
3049 0 OXIDE.EA.1: Oxide enclosed area must be >= 0.10 um
3053 0 OXIDE.X.1: Oxide must be covered by Nimp or Pimp or Nzvt
3059 0 OXIDER.SE.1: SiProt to Oxide resistor Cont spacing must be >= 0.24 um
3060 0 OXIDER.SE.1: SiProt to Oxide resistor Cont spacing must be >= 0.24 um
3063 0 OXIDER.SE.2: Oxide resistor to Nimp spacing must be >= 0.3 um
3064 0 OXIDER.SE.2: Oxide resistor to Nimp spacing must be >= 0.3 um
3067 0 OXIDER.SE.2: Oxide resistor to Pimp spacing must be >= 0.3 um
3068 0 OXIDER.SE.2: Oxide resistor to Pimp spacing must be >= 0.3 um
3070 0 OXIDER.E.1: SiProt to Oxide resistor enclosure must be >= 0.25 um
3072 0 OXIDER.X.1: Oxide resistors must have N+ or P+ Implant
3073 0 OXIDETHK.W.1: Oxide_thk width must be >= 0.7 um
3075 0 OXIDETHK.SP.1: Oxide_thk to Oxide_thk spacing must be >= 0.35 um
3077 0 OXIDETHK.SP.2: Oxide_thk (bent 45 degree) to Oxide_thk spacing must be >= 0.75 um
3079 0 OXIDETHK.SE.1: 2.5V N+ Oxide to 2.5V N+ Oxide spacing must be >= 0.20 um
3081 0 OXIDETHK.SE.2: 2.5V P+ Oxide to 2.5V P+ Oxide spacing must be >= 0.20 um
3086 0 OXIDETHK.SE.3: 2.5V N+ Oxide to 2.5V P+ Oxide spacing must be >= 0.25 um
3088 0 OXIDETHK.E.1: Oxide_thk to Oxide enclosure must be >= 0.30 um
3095 0 OXIDETHK.SE.5: Oxide_thk to Poly gate spacing must be >= 0.34 um
3096 0 OXIDETHK.SE.5: Oxide_thk to Poly gate spacing must be >= 0.34 um
3098 0 OXIDETHK.E.2: Oxide_thk to Poly gate enclosure must be >= 0.36 um
3099 0 NHVT.X.2: Nhvt is NOT allowed on Nwell
3100 0 NHVT.X.3: Nhvt is NOT allowed on P+ Oxide
3101 0 NHVT.X.4: Nhvt is NOT allowed on Nzvt
3102 0 PHVT.X.2: Phvt is NOT allowed outside Nwell
3103 0 PHVT.X.3: Phvt is NOT allowed on N+ Oxide
3104 0 PHVT.X.4: Phvt is NOT allowed on Nzvt
3105 0 NZVT.W.1: Nzvt width must be >= 0.7 um
3107 0 NZVT.SP.1: Nzvt to Nzvt spacing must be >= 0.6 um
3110 0 NZVT.SE.1: Nzvt to Oxide spacing must be >= 0.28 um
3111 0 NZVT.SE.1: Nzvt to Oxide spacing must be >= 0.28 um
3112 0 NZVT.SE.2: Nzvt to Nwell spacing must be >= 1.2 um
3113 0 NZVT.SE.2: Nzvt to Nwell spacing must be >= 1.2 um
3116 0 NZVT.E.1: Poly to Oxide enclosure must be >= 0.2 um
3119 0 NZVT.L.1: Native Device Poly gate length must be >= 0.9 um
3123 0 NZVT.W.2: Native Device Poly gate width must be >= 0.65 um
3125 0 NZVT.X.3: P+ Oxide is NOT allowed in Nzvt
3128 0 POLY.W.1: 1.2V N+ Poly gate length must be >= 0.1 um
3131 0 POLY.W.2: 1.2V P+ Poly gate length must be >= 0.1 um
3135 0 POLY.W.3: 2.5V N+ Poly gate length must be >= 0.28 um
3140 0 POLY.W.4: 2.5V P+ Poly gate length must be >= 0.28 um
3143 0 POLY.W.5: Poly interconnect width must be >= 0.1 um
3147 0 POLY.SP.1: Poly resistor to Poly resistor spacing must be >= 0.6 um
3149 0 POLY.SP.2: Poly gate to Poly gate spacing must be >= 0.12 um
3151 0 POLY.SP.3: Poly interconnect to Poly interconnect spacing must be >= 0.12 um
3153 0 POLY.E.1: Poly to N+ Oxide enclosure must be >= 0.18 um
3155 0 POLY.E.2: Poly to P+ Oxide enclosure must be >= 0.18 um
3156 0 POLY.SE.1_POLY.SE.2: Poly to Oxide spacing must be >= 0.1 um
3158 0 POLY.E.3: Oxide to Poly enclosure must be >= 0.2 um
3160 0 POLY.W.6: Bent Poly width must be >= 0.18 um
3162 0 POLY.SP.4: Bent Poly to bent Poly spacing must be >= 0.22 um
3163 0 POLY.X.1: Poly gate cannot have bends
3164 0 POLY.X.2: Poly resistor cannot have bends
3165 0 POLY.A.1: Poly area must be >= 0.1 um
3171 0 POLYR.SE.1: SiProt to Poly resistor Cont spacing must be >= 0.24 um
3172 0 POLYR.SE.1: SiProt to Poly resistor Cont spacing must be >= 0.24 um
3174 0 POLYR.E.1: SiProt to Poly resistor enclosure must be >= 0.28 um
3176 0 POLYR.E.2: Nimp to Poly used in resistor enclosure must be >= 0.15 um
3178 0 POLYR.E.2: Nimp to Poly used in resistor enclosure must be >= 0.15 um
3180 0 POLYR.E.3: Pimp to Poly used in resistor enclosure must be >= 0.15 um
3182 0 POLYR.E.3: Pimp to Poly used in resistor enclosure must be >= 0.15 um
3184 0 POLYR.SE.2: Poly resistor to Nimp spacing must be >= 0.3 um
3185 0 POLYR.SE.2: Poly resistor to Nimp spacing must be >= 0.3 um
3186 0 POLYR.SE.2: Poly resistor to Nzvt spacing must be >= 0.3 um
3187 0 POLYR.SE.2: Poly resistor to Nzvt spacing must be >= 0.3 um
3189 0 POLYR.SE.2: Poly resistor to Pimp spacing must be >= 0.3 um
3190 0 POLYR.SE.2: Poly resistor to Pimp spacing must be >= 0.3 um
3191 0 POLYR.X.1: Poly resistors must have N+ or P+ Implant
3192 0 NIMP.W.1: Nimp width must be >= 0.24 um
3194 0 NIMP.SP.1: Nimp to Nimp spacing must be >= 0.24 um
3197 0 NIMP.E.1: Nimp to Oxide enclosure must be >= 0.14 um
3198 0 NIMP.O.1: Nimp to Oxide overlap must be >= 0.16 um
3206 0 NIMP.SE.1: Nimp to P+ Oxide spacing must be >= 0.16 um
3207 0 NIMP.SE.1: Nimp to P+ Oxide spacing must be >= 0.16 um
3210 0 NIMP.E.2: Nimp to Oxide (Nwell tie) enclosure must be >= 0.02 um
3214 0 NIMP.E.3: Nimp to Poly gate enclosure must be >= 0.18 um
3220 0 NIMP.E.4: Nimp to gate end enclosure must be >= 0.18 um
3222 0 NIMP.E.4: Nimp to gate end enclosure must be >= 0.18 um
3231 0 NIMP.SE.2: Nimp to P+ Oxide spacing must be >= 0.02 um
3232 0 NIMP.SE.2: Nimp to P+ Oxide spacing must be >= 0.02 um
3233 0 NIMP.A.1: Nimp area must be >= 0.15 um
3237 0 NIMP.EA.1: Area in Nimp ring must be >= 0.16 um
3240 0 NIMP.SE.3: Nimp to P+ gate spacing must be >= 0.18 um
3241 0 NIMP.SE.3: Nimp to P+ gate spacing must be >= 0.18 um
3242 0 NIMP.X.1: Nimp is NOT allowed over Pimp
3243 0 PIMP.W.1: Pimp width must be >= 0.24 um
3245 0 PIMP.SP.1: Pimp to Pimp spacing must be >= 0.24 um
3247 0 PIMP.E.1: Pimp to Oxide enclosure must be >= 0.14 um
3248 0 PIMP.O.1: Pimp to Oxide overlap must be >= 0.16 um
3256 0 PIMP.SE.1: Pimp to N+ Oxide spacing must be >= 0.16 um
3257 0 PIMP.SE.1: Pimp to N+ Oxide spacing must be >= 0.16 um
3259 0 PIMP.E.2: Pimp to Oxide (substrate tie) enclosure must be >= 0.02 um
3263 0 PIMP.E.3: Pimp to Poly gate enclosure must be >= 0.18 um
3266 0 PIMP.E.4: Pimp to gate end enclosure must be >= 0.18 um
3268 0 PIMP.E.4: Pimp to gate end enclosure must be >= 0.18 um
3277 0 PIMP.SE.2: Pimp to N+ Oxide spacing must be >= 0.02 um
3278 0 PIMP.SE.2: Pimp to N+ Oxide spacing must be >= 0.02 um
3279 0 PIMP.A.1: Pimp area must be >= 0.15 um
3283 0 PIMP.EA.1: Area in Pimp ring must be >= 0.16 um
3286 0 PIMP.SE.3: Pimp to N+ gate spacing must be >= 0.18 um
3287 0 PIMP.SE.3: Pimp to N+ gate spacing must be >= 0.18 um
3289 0 CONT.W.1: Cont shapes must be 0.12x0.12 rectangles
3291 0 CONT.SP.1: Cont to Cont spacing must be >= 0.14 um
3294 0 CONT.SP.2: Cont to Cont (in array) spacing must be >= 0.16 um
3297 0 CONT.SE.1: Cont to gate spacing must be >= 0.10 um
3298 0 CONT.SE.1: Cont to gate spacing must be >= 0.10 um
3304 0 CONT.SE.2: Cont to 2.5V gate spacing must be >= 0.12 um
3305 0 CONT.SE.2: Cont to 2.5V gate spacing must be >= 0.12 um
3307 0 CONT.SE.3: Poly Cont to Oxide spacing must be >= 0.12 um
3308 0 CONT.SE.3: Poly Cont to Oxide spacing must be >= 0.12 um
3313 0 CONT.SE.4: Poly Cont to Oxide spacing must be >= 0.14 um
3314 0 CONT.SE.4: Poly Cont to Oxide spacing must be >= 0.14 um
3316 0 CONT.E.1: Oxide to Cont enclosure must be >= 0.06 um
3318 0 CONT.E.1: Oxide to Cont enclosure must be >= 0.06 um
3320 0 CONT.E.2: Poly to Cont enclosure must be >= 0.04 um
3322 0 CONT.E.2: Poly to Cont enclosure must be >= 0.04 um
3325 0 CONT.E.3: Poly to Cont enclosure on at least two opposite sides must be >= 0.06 um
3327 0 CONT.E.4: Nimp to Cont enclosure must be >= 0.06 um
3329 0 CONT.E.4: Nimp to Cont enclosure must be >= 0.06 um
3331 0 CONT.E.4: Pimp to Cont enclosure must be >= 0.06 um
3333 0 CONT.E.4: Pimp to Cont enclosure must be >= 0.06 um
3335 0 CONT.X.1: Cont on gate is NOT allowed
3338 0 CONT.X.2: Nimp edge is NOT allowed on Oxide Cont
3342 0 CONT.X.2: Pimp edge is NOT allowed on Oxide Cont
3344 0 CONT.X.3: Cont must be covered by Oxide or Poly
3345 0 SIPROT.W.1: SiProt width must be >= 0.44 um
3347 0 SIPROT.SP.1: SiProt to SiProt spacing must be >= 0.44 um
3350 0 SIPROT.SE.1: SiProt to Cont spacing must be >= 0.24 um
3351 0 SIPROT.SE.1: SiProt to Cont spacing must be >= 0.24 um
3352 0 SIPROT.SE.2: SiProt to Oxide spacing must be >= 0.24 um
3356 0 SIPROT.SE.3: SiProt to Poly gate spacing must be >= 0.44 um
3357 0 SIPROT.SE.3: SiProt to Poly gate spacing must be >= 0.44 um
3359 0 SIPROT.E.2: Oxide to SiProt enclosure must be >= 0.24 um
3363 0 SIPROT.E.1: SiProt to Oxide enclosure must be >= 0.25 um
3365 0 SIPROT.E.3: SiProt to Poly enclosure must be >= 0.28 um
3366 0 SIPROT.A.1: SiProt area must be >= 1.2 um
3367 0 SIPROT.SE.4: SiProt to Poly (on field) spacing must be >= 0.35 um
3371 0 SIPROT.EA.1: Area in SiProt ring must be >= 1.2 um
3372 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
3374 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
3378 0 METAL2.E.2: Metal2 to Via1 enclosure on opposite sides must be >= 0.06 um
3379 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
3381 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
3385 0 METAL3.E.2: Metal3 to Via2 enclosure on opposite sides must be >= 0.06 um
3386 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
3388 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
3392 0 METAL4.E.2: Metal4 to Via3 enclosure on opposite sides must be >= 0.06 um
3393 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
3395 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
3399 0 METAL5.E.2: Metal5 to Via4 enclosure on opposite sides must be >= 0.06 um
3400 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
3402 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
3406 0 METAL6.E.2: Metal6 to Via5 enclosure on opposite sides must be >= 0.06 um
3407 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
3409 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
3413 0 METAL7.E.2: Metal7 to Via6 enclosure on opposite sides must be >= 0.06 um
3414 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.05 um
3416 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.05 um
3420 0 METAL8.E.2: Metal8 to Via7 enclosure on opposite sides must be >= 0.1 um
3421 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.05 um
3423 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.05 um
3427 0 METAL9.E.2: Metal9 to Via8 enclosure on opposite sides must be >= 0.1 um
3428 0 METAL1.E.1: Metal1 to Cont enclosure must be >= 0.00 um
3432 0 METAL1.E.2: Metal1 to Cont enclosure on opposite sides must be >= 0.06 um
3433 0 METAL1.W.1: Metal1 width must be >= 0.12 um
3434 0 METAL2.W.1: Metal2 width must be >= 0.14 um
3435 0 METAL3.W.1: Metal3 width must be >= 0.14 um
3436 0 METAL4.W.1: Metal4 width must be >= 0.14 um
3437 0 METAL5.W.1: Metal5 width must be >= 0.14 um
3438 0 METAL6.W.1: Metal6 width must be >= 0.14 um
3439 0 METAL7.W.1: Metal7 width must be >= 0.14 um
3440 0 METAL8.W.1: Metal8 width must be >= 0.44 um
3441 0 METAL9.W.1: Metal9 width must be >= 0.44 um
3445 0 METAL1.W.2: Metal1 width must be <= 12.0 um
3449 0 METAL2.W.2: Metal2 width must be <= 12.0 um
3453 0 METAL3.W.2: Metal3 width must be <= 12.0 um
3457 0 METAL4.W.2: Metal4 width must be <= 12.0 um
3461 0 METAL5.W.2: Metal5 width must be <= 12.0 um
3465 0 METAL6.W.2: Metal6 width must be <= 12.0 um
3468 0 METAL7.W.2: Metal7 width must be <= 12.0 um
3470 0 METAL8.W.2: Metal8 width must be <= 12.0 um
3472 0 METAL9.W.2: Metal9 width must be <= 12.0 um
3474 0 METAL1.SP.1.1: Metal1 to Metal1 spacing must be >= 0.12 um
3476 0 METAL2.SP.1.1: Metal2 to Metal2 spacing must be >= 0.14 um
3478 0 METAL3.SP.1.1: Metal3 to Metal3 spacing must be >= 0.14 um
3480 0 METAL4.SP.1.1: Metal4 to Metal4 spacing must be >= 0.14 um
3482 0 METAL5.SP.1.1: Metal5 to Metal5 spacing must be >= 0.14 um
3484 0 METAL6.SP.1.1: Metal6 to Metal6 spacing must be >= 0.14 um
3486 0 METAL7.SP.1.1: Metal7 to Metal7 spacing must be >= 0.14 um
3488 0 METAL8.SP.1.1: Metal8 to Metal8 spacing must be >= 0.40 um
3490 0 METAL9.SP.1.1: Metal9 to Metal9 spacing must be >= 0.40 um
3495 0 METAL1.SP.1.2: Metal1 to Metal1 spacing must be >= 0.18 um
3501 0 METAL2.SP.1.2: Metal2 to Metal2 spacing must be >= 0.20 um
3507 0 METAL3.SP.1.2: Metal3 to Metal3 spacing must be >= 0.20 um
3513 0 METAL4.SP.1.2: Metal4 to Metal4 spacing must be >= 0.20 um
3519 0 METAL5.SP.1.2: Metal5 to Metal5 spacing must be >= 0.20 um
3525 0 METAL6.SP.1.2: Metal6 to Metal6 spacing must be >= 0.20 um
3531 0 METAL7.SP.1.2: Metal7 to Metal7 spacing must be >= 0.20 um
3537 0 METAL1.SP.1.3: Metal1 to Metal1 spacing must be >= 0.50 um
3543 0 METAL2.SP.1.3: Metal2 to Metal2 spacing must be >= 0.50 um
3549 0 METAL3.SP.1.3: Metal3 to Metal3 spacing must be >= 0.50 um
3555 0 METAL4.SP.1.3: Metal4 to Metal4 spacing must be >= 0.50 um
3561 0 METAL5.SP.1.3: Metal5 to Metal5 spacing must be >= 0.50 um
3567 0 METAL6.SP.1.3: Metal6 to Metal6 spacing must be >= 0.50 um
3573 0 METAL7.SP.1.3: Metal7 to Metal7 spacing must be >= 0.50 um
3579 0 METAL8.SP.1.2: Metal8 to Metal8 spacing must be >= 0.50 um
3585 0 METAL9.SP.1.2: Metal9 to Metal9 spacing must be >= 0.50 um
3591 0 METAL1.SP.1.4: Metal1 to Metal1 spacing must be >= 0.90 um
3597 0 METAL2.SP.1.4: Metal2 to Metal2 spacing must be >= 0.90 um
3603 0 METAL3.SP.1.4: Metal3 to Metal3 spacing must be >= 0.90 um
3609 0 METAL4.SP.1.4: Metal4 to Metal4 spacing must be >= 0.90 um
3615 0 METAL5.SP.1.4: Metal5 to Metal5 spacing must be >= 0.90 um
3621 0 METAL6.SP.1.4: Metal6 to Metal6 spacing must be >= 0.90 um
3627 0 METAL7.SP.1.4: Metal7 to Metal7 spacing must be >= 0.90 um
3633 0 METAL8.SP.1.3: Metal8 to Metal8 spacing must be >= 0.90 um
3639 0 METAL9.SP.1.3: Metal9 to Metal9 spacing must be >= 0.90 um
3645 0 METAL1.SP.1.5: Metal1 to Metal1 spacing must be >= 1.50 um
3651 0 METAL2.SP.1.5: Metal2 to Metal2 spacing must be >= 1.50 um
3657 0 METAL3.SP.1.5: Metal3 to Metal3 spacing must be >= 1.50 um
3663 0 METAL4.SP.1.5: Metal4 to Metal4 spacing must be >= 1.50 um
3669 0 METAL5.SP.1.5: Metal5 to Metal5 spacing must be >= 1.50 um
3675 0 METAL6.SP.1.5: Metal6 to Metal6 spacing must be >= 1.50 um
3681 0 METAL7.SP.1.5: Metal7 to Metal7 spacing must be >= 1.50 um
3687 0 METAL8.SP.1.4: Metal8 to Metal8 spacing must be >= 1.50 um
3693 0 METAL9.SP.1.4: Metal9 to Metal9 spacing must be >= 1.50 um
3699 0 METAL1.SP.1.6: Metal1 to Metal1 spacing must be >= 2.50 um
3705 0 METAL2.SP.1.6: Metal2 to Metal2 spacing must be >= 2.50 um
3711 0 METAL3.SP.1.6: Metal3 to Metal3 spacing must be >= 2.50 um
3717 0 METAL4.SP.1.6: Metal4 to Metal4 spacing must be >= 2.50 um
3723 0 METAL5.SP.1.6: Metal5 to Metal5 spacing must be >= 2.50 um
3729 0 METAL6.SP.1.6: Metal6 to Metal6 spacing must be >= 2.50 um
3735 0 METAL7.SP.1.6: Metal7 to Metal7 spacing must be >= 2.50 um
3741 0 METAL8.SP.1.5: Metal8 to Metal8 spacing must be >= 2.50 um
3747 0 METAL9.SP.1.5: Metal9 to Metal9 spacing must be >= 2.50 um
3750 0 METAL1.L.1: Metal1 non-90 degree segments must be >= 0.18 um
3753 0 METAL2.L.1: Metal2 non-90 degree segments must be >= 0.20 um
3756 0 METAL3.L.1: Metal3 non-90 degree segments must be >= 0.20 um
3759 0 METAL4.L.1: Metal4 non-90 degree segments must be >= 0.20 um
3762 0 METAL5.L.1: Metal5 non-90 degree segments must be >= 0.20 um
3765 0 METAL6.L.1: Metal6 non-90 degree segments must be >= 0.20 um
3768 0 METAL7.L.1: Metal7 non-90 degree segments must be >= 0.20 um
3770 0 METAL1.SP.2: Metal1 to bent Metal1 spacing must be >= 0.16 um
3771 0 METAL1.W.3: Bent Metal1 (45 degree angle) width must be >= 0.14
3772 0 METAL2.SP.2: Metal2 to bent Metal2 spacing must be >= 0.18 um
3773 0 METAL2.W.3: Bent Metal2 (45 degree angle) width must be >= 0.16
3774 0 METAL3.SP.2: Metal3 to bent Metal3 spacing must be >= 0.18 um
3775 0 METAL3.W.3: Bent Metal3 (45 degree angle) width must be >= 0.16
3776 0 METAL4.SP.2: Metal4 to bent Metal4 spacing must be >= 0.18 um
3777 0 METAL4.W.3: Bent Metal4 (45 degree angle) width must be >= 0.16
3778 0 METAL5.SP.2: Metal5 to bent Metal5 spacing must be >= 0.18 um
3779 0 METAL5.W.3: Bent Metal5 (45 degree angle) width must be >= 0.16
3780 0 METAL6.SP.2: Metal6 to bent Metal6 spacing must be >= 0.18 um
3781 0 METAL6.W.3: Bent Metal6 (45 degree angle) width must be >= 0.16
3782 0 METAL7.SP.2: Metal7 to bent Metal7 spacing must be >= 0.18 um
3783 0 METAL7.W.3: Bent Metal7 (45 degree angle) width must be >= 0.16
3784 0 METAL1.A.1: Metal1 area must be >= 0.07 um
3785 0 METAL2.A.1: Metal2 area must be >= 0.08 um
3786 0 METAL3.A.1: Metal3 area must be >= 0.08 um
3787 0 METAL4.A.1: Metal4 area must be >= 0.08 um
3788 0 METAL5.A.1: Metal5 area must be >= 0.08 um
3789 0 METAL6.A.1: Metal6 area must be >= 0.08 um
3790 0 METAL7.A.1: Metal7 area must be >= 0.08 um
3791 0 METAL8.A.1: Metal8 area must be >= 0.2 um
3792 0 METAL9.A.1: Metal9 area must be >= 0.2 um
3794 0 VIA1.W.1: Via1 shapes must be 0.14x0.14 rectangles
3796 0 VIA1.SP.1: Via1 to Via1 spacing must be >= 0.15 um
3808 0 VIA1.SP.2: Via1 to Via1 spacing must be >= 0.20 um
3810 0 VIA2.W.1: Via2 shapes must be 0.14x0.14 rectangles
3812 0 VIA2.SP.1: Via2 to Via2 spacing must be >= 0.15 um
3824 0 VIA2.SP.2: Via2 to Via2 spacing must be >= 0.20 um
3826 0 VIA3.W.1: Via3 shapes must be 0.14x0.14 rectangles
3828 0 VIA3.SP.1: Via3 to Via3 spacing must be >= 0.15 um
3840 0 VIA3.SP.2: Via3 to Via3 spacing must be >= 0.20 um
3842 0 VIA4.W.1: Via4 shapes must be 0.14x0.14 rectangles
3844 0 VIA4.SP.1: Via4 to Via4 spacing must be >= 0.15 um
3856 0 VIA4.SP.2: Via4 to Via4 spacing must be >= 0.20 um
3858 0 VIA5.W.1: Via5 shapes must be 0.14x0.14 rectangles
3860 0 VIA5.SP.1: Via5 to Via5 spacing must be >= 0.15 um
3872 0 VIA5.SP.2: Via5 to Via5 spacing must be >= 0.20 um
3874 0 VIA6.W.1: Via6 shapes must be 0.14x0.14 rectangles
3876 0 VIA6.SP.1: Via6 to Via6 spacing must be >= 0.15 um
3888 0 VIA6.SP.2: Via6 to Via6 spacing must be >= 0.20 um
3890 0 VIA7.W.1: Via7 shapes must be 0.36x0.36 rectangles
3892 0 VIA7.SP.1: Via7 to Via7 spacing must be >= 0.36 um
3894 0 VIA8.W.1: Via8 shapes must be 0.36x0.36 rectangles
3896 0 VIA8.SP.1: Via8 to Via8 spacing must be >= 0.36 um
3897 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
3899 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
3903 0 VIA1.E.2: Metal1 to Via1 enclosure on opposite sides must be >= 0.06 um
3904 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
3906 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
3910 0 VIA2.E.2: Metal2 to Via2 enclosure on opposite sides must be >= 0.06 um
3911 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
3913 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
3917 0 VIA3.E.2: Metal3 to Via3 enclosure on opposite sides must be >= 0.06 um
3918 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
3920 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
3924 0 VIA4.E.2: Metal4 to Via4 enclosure on opposite sides must be >= 0.06 um
3925 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
3927 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
3931 0 VIA5.E.2: Metal5 to Via5 enclosure on opposite sides must be >= 0.06 um
3932 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
3934 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
3938 0 VIA6.E.2: Metal6 to Via6 enclosure on opposite sides must be >= 0.06 um
3939 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.03 um
3941 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.03 um
3945 0 VIA7.E.2: Metal7 to Via7 enclosure on opposite sides must be >= 0.08 um
3946 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.03 um
3948 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.03 um
3952 0 VIA8.E.2: Metal8 to Via8 enclosure on opposite sides must be >= 0.08 um
4219 0 LATCHUP.1: P+SD to NW tap spacing must be <= 25.0 um
4600 0 LATCHUP.2: N+SD to Psub tap spacing must be <= 25.0 um
4603 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 18.0 um
4604 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 18.0 um
4609 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 50.0 um when not blocked by a double guard ring
4613 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 50.0 um when not blocked by a double guard ring
4615 0 MSLOT1.W.1_MSLOT1.L.1: Metal1 Slot width/length must be >= 2.0 um
4617 0 MSLOT1.SP.1: Metal1 Slot to Metal1 Slot spacing must be >= 0.12 um
4619 0 MSLOT2.W.1_MSLOT2.L.1: Metal2 Slot width/length must be >= 2.0 um
4621 0 MSLOT2.SP.1: Metal2 Slot to Metal2 Slot spacing must be >= 0.14 um
4623 0 MSLOT3.W.1_MSLOT3.L.1: Metal3 Slot width/length must be >= 2.0 um
4625 0 MSLOT3.SP.1: Metal3 Slot to Metal3 Slot spacing must be >= 0.14 um
4627 0 MSLOT4.W.1_MSLOT4.L.1: Metal4 Slot width/length must be >= 2.0 um
4629 0 MSLOT4.SP.1: Metal4 Slot to Metal4 Slot spacing must be >= 0.14 um
4631 0 MSLOT5.W.1_MSLOT5.L.1: Metal5 Slot width/length must be >= 2.0 um
4633 0 MSLOT5.SP.1: Metal5 Slot to Metal5 Slot spacing must be >= 0.14 um
4635 0 MSLOT6.W.1_MSLOT6.L.1: Metal6 Slot width/length must be >= 2.0 um
4637 0 MSLOT6.SP.1: Metal6 Slot to Metal6 Slot spacing must be >= 0.14 um
4639 0 MSLOT7.W.1_MSLOT7.L.1: Metal7 Slot width/length must be >= 2.0 um
4641 0 MSLOT7.SP.1: Metal7 Slot to Metal7 Slot spacing must be >= 0.14 um
4643 0 MSLOT8.W.1_MSLOT8.L.1: Metal8 Slot width/length must be >= 2.0 um
4645 0 MSLOT8.SP.1: Metal8 Slot to Metal8 Slot spacing must be >= 0.44 um
4647 0 MSLOT9.W.1_MSLOT9.L.1: Metal9 Slot width/length must be >= 2.0 um
4649 0 MSLOT9.SP.1: Metal9 Slot to Metal9 Slot spacing must be >= 0.44 um
4653 0 ESD.1: ESD gate width must be >= 15.0 um and <= 65.0 um
4655 0 ESD.4: N+ source should connect to Pad or Bulk
4656 0 ESD.4: P+ source should connect to Pad or Nwell
4657 0 ESD.5: NMOS I/O and ESD devices must be inside P+ rings
4658 0 ESD.6: PMOS I/O and ESD devices must be inside N+ rings
4659 0 ESD.7: P+ taps can NOT butt NMOS I/O and ESD devices
4660 0 ESD.7: N+ taps can NOT butt PMOS I/O and ESD devices
4661 0 ESD.8: N+ drains must be non-salicided (except Contact area)
4662 0 ESD.8: P+ drains must be non-salicided (except Contact area)
4665 0 ESD.11: SiProt to Poly gate overlap must be >= 0.05 um
4667 0 ESD.12: SiProt to Poly gate enclosure must be >= 1.8 um
4669 0 ESD.13: SiProt to Oxide overlap must be >= 1.8 um
4673 0 ESD.14: ESD gate length must be == 0.3 um
4678 0 ESD.15: Poly gate to Cont spacing must be >= 0.25 um
4679 0 ESD.15: Poly gate to Cont spacing must be >= 0.25 um
4681 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
4683 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
4684 0 BONDPAD.SP.2: Bondpad Metal1 to Metal1 spacing must be >= 3.0 um
4686 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
4688 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
4689 0 BONDPAD.SP.2: Bondpad Metal2 to Metal2 spacing must be >= 3.0 um
4691 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
4693 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
4694 0 BONDPAD.SP.2: Bondpad Metal3 to Metal3 spacing must be >= 3.0 um
4696 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
4698 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
4699 0 BONDPAD.SP.2: Bondpad Metal4 to Metal4 spacing must be >= 3.0 um
4701 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
4703 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
4704 0 BONDPAD.SP.2: Bondpad Metal5 to Metal5 spacing must be >= 3.0 um
4706 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
4708 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
4709 0 BONDPAD.SP.2: Bondpad Metal6 to Metal6 spacing must be >= 3.0 um
4711 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
4713 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
4714 0 BONDPAD.SP.2: Bondpad Metal7 to Metal7 spacing must be >= 3.0 um
4716 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
4718 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
4719 0 BONDPAD.SP.2: Bondpad Metal8 to Metal8 spacing must be >= 3.0 um
4721 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
4723 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
4724 0 BONDPAD.SP.2: Bondpad Metal9 to Metal9 spacing must be >= 3.0 um
4727 0 BONDPAD.W.1: Bondpad width must be >= 52.0 um
4729 0 BONDPAD.W.1: Bondpad width must be >= 52.0 um
4732 0 BONDPAD.SP.1: Bondpad to Bondpad spacing must be >= 8.0 um
4734 0 BONDPAD.B.1: Bondpad Metal1 beveled segments must be >= 1.8 um and <= 3.2 um
4737 0 BONDPAD.B.1: Bondpad Metal2 beveled segments must be >= 1.8 um and <= 3.2 um
4740 0 BONDPAD.B.1: Bondpad Metal3 beveled segments must be >= 1.8 um and <= 3.2 um
4743 0 BONDPAD.B.1: Bondpad Metal4 beveled segments must be >= 1.8 um and <= 3.2 um
4746 0 BONDPAD.B.1: Bondpad Metal5 beveled segments must be >= 1.8 um and <= 3.2 um
4749 0 BONDPAD.B.1: Bondpad Metal6 beveled segments must be >= 1.8 um and <= 3.2 um
4752 0 BONDPAD.B.1: Bondpad Metal7 beveled segments must be >= 1.8 um and <= 3.2 um
4755 0 BONDPAD.B.1: Bondpad Metal8 beveled segments must be >= 1.8 um and <= 3.2 um
4758 0 BONDPAD.B.1: Bondpad Metal9 beveled segments must be >= 1.8 um and <= 3.2 um
4762 0 BONDPAD.SP.3: Bondpad Via1 to Bondpad Via1 spacing must be >= 0.22 um
4765 0 BONDPAD.SP.3: Bondpad Via2 to Bondpad Via2 spacing must be >= 0.22 um
4768 0 BONDPAD.SP.3: Bondpad Via3 to Bondpad Via3 spacing must be >= 0.22 um
4771 0 BONDPAD.SP.3: Bondpad Via4 to Bondpad Via4 spacing must be >= 0.22 um
4774 0 BONDPAD.SP.3: Bondpad Via5 to Bondpad Via5 spacing must be >= 0.22 um
4777 0 BONDPAD.SP.3: Bondpad Via6 to Bondpad Via6 spacing must be >= 0.22 um
4780 0 BONDPAD.SP.4: Bondpad Via7 to Bondpad Via7 spacing must be >= 0.54 um
4783 0 BONDPAD.SP.4: Bondpad Via8 to Bondpad Via8 spacing must be >= 0.54 um
4785 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
4787 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
4789 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
4791 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
4793 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
4795 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
4797 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
4799 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
4801 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
4803 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
4805 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
4807 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
4809 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.09 um
4811 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.09 um
4813 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.09 um
4815 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.09 um
4817 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
4819 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
4821 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
4823 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
4825 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
4827 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
4829 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
4831 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
4833 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
4835 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
4837 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
4839 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
4841 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.09 um
4843 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.09 um
4845 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.09 um
4847 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.09 um
4848 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
4849 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
4850 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
4851 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
4852 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
4853 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
4854 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
4855 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
4856 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
4857 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
4858 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
4859 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
4860 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
4861 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
4862 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
4863 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
4865 0 BONDPAD.SP.7: Bondpad Via1 array to Bondpad Via1 array spacing must be >= 1.1 um
4867 0 BONDPAD.SP.7: Bondpad Via2 array to Bondpad Via2 array spacing must be >= 1.1 um
4869 0 BONDPAD.SP.7: Bondpad Via3 array to Bondpad Via3 array spacing must be >= 1.1 um
4871 0 BONDPAD.SP.7: Bondpad Via4 array to Bondpad Via4 array spacing must be >= 1.1 um
4873 0 BONDPAD.SP.7: Bondpad Via5 array to Bondpad Via5 array spacing must be >= 1.1 um
4875 0 BONDPAD.SP.7: Bondpad Via6 array to Bondpad Via6 array spacing must be >= 1.1 um
4877 0 BONDPAD.SP.7: Bondpad Via7 array to Bondpad Via7 array spacing must be >= 1.1 um
4879 0 BONDPAD.SP.7: Bondpad Via8 array to Bondpad Via8 array spacing must be >= 1.1 um
4882 0 OXIDER.W.1.1: Oxide resistor width must be >= 0.2 um
4885 0 POLYR.W.1.1: Poly resistor width must be >= 0.2 um
